
###
GET http://localhost:9129/list?app=app1&env=dev&namespace=public
Accept: application/json

###
POST http://localhost:9129/update?app=app1&env=dev&namespace=public
Content-Type: application/json

{
  "a": "dev200",
  "c": "ccc100",
  "d": "d100"
}

